### ISSUE TITLE
Unable to Pause the Instance via the API

### ISSUE THREAD

**Issue by prawiraelang** [jarvislabsai/jarviscloud#1]
I have been using JarvisLabs for the past few months and I am familiar with your API for pausing instances. However, recently I have been unable to pause the instance as I usually do.

Below is how to reproduce the error. I just followed your documentation [here](https://jarvislabs.ai/docs/getting-started/pause-instance/).

```
from jarviscloud import jarviscloud
jarviscloud.pause()
```

I ran the above code on JupyterLab.

The error messages are as below:
```
ConnectionError: HTTPSConnectionPool(host='backendprod.jarvislabs.ai', port=8000): Max retries exceeded with url: /pause (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9b8aa65780>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Is there something wrong with the way I am using this API, or could there be a bug on your side?

**Comment by svishnu88** [comment]
Hi, We fixed it now. It should be working now.

**Comment by prawiraelang** [comment]
Hi!
Thank you for resolving this issue. I have tried it, and it's now working.
